---
# tasks file for lacework-agent-ansible-role

- name: Ensure proper configuration
  assert:
    that:
      - lacework_accessToken is defined
      # - lacework_accessToken | length > 32
    fail_msg: |
      'lacework_accessToken' was not configured.
      Please see https://support.lacework.com/hc/en-us/articles/360011403853-Generate-API-Access-Keys-and-Tokens#:~:text=To%20create%20an%20API%20key,open%20it%20in%20an%20editor.
    success_msg: "'lacework_accessToken' is properly set."

- name: Ensure supported architecture
  assert:
    that:
      - ansible_userspace_bits|int in [64]
    fail_msg: 'Lacework Agent requires a 64-bit system'

- name: Install Lacework Agent (package)
  block:
    - name: perform agent installation for rpm based systems
      include_tasks: prep-rpm.yml
      when:
        - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

    - name: perform agent installation for deb based systems
      include_tasks: prep-deb.yml
      when:
        - ansible_pkg_mgr == 'apt'

    - name: install the lacework datacollector (apt/rpm)
      package:
        name: "{{ lacework_package_name }}"
        state: latest
  when:
    - not lacework_skip_package_install | bool

- name: Install Lacework Agent (install.sh)
  block:
    - name: perform agent install with install.sh
      include_tasks: prep-install-sh.yml
  when:
    - "not lacework_skip_install_sh_install | bool"

- name: generate config.json
  template:
    src: config.json.j2
    dest: /var/lib/lacework/config/config.json
    owner: root
    group: root
    mode: "0644"
  notify: restart Lacework Agent (datacollector) service

- name: enable Lacework Agent (datacollector) service
  service:
    name: datacollector
    enabled: yes
  when: not lacework_skip_service_enable | bool
